### PR TITLE
perf: :zap: :zap: :zap: remove buffer

### PR DESCRIPTION
**Pull request by CGQAQ**
# CAUTION: PERFORMANCE SUPERCHARGED! :zap:  :zap:  :zap: 

Not really sure what's goin' on, but tests all passed, who knows

image

DO NOT MERGE THIS! WAIT UNTIL PARSER TESTS ALL PASSED!

Signed-off-by: CGQAQ <m.jason.liu@outlook.com>

### CODE REVIEW

**Comment by CGQAQ** [comment]
NOT WORKING

**Comment by justjavac** [comment]
Maybe the test cases are not fully covered

**Comment by CGQAQ** [comment]
I have made a PR at [PostCSS Repo](https://github.com/postcss/postcss/pull/1654), we'll see. :smile:

**Comment by justjavac** [comment]
I have found a case `url(foo)(`

**Pull request closed without merging**
